<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<HTML LANG=en-US>
<HEAD>
<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=ISO-8859-1">
<TITLE>US DOT Vinyl Stickers - Numbers - $7.99 per set - Quick Order Form - Google Checkout</TITLE>
<LINK REV="made" href="mailto:arronlorenz@dotlettering.com">
<META NAME="keywords" CONTENT="USDOT, US DOT, lettering, numbers, vinyl, stickers, regulation, truck decals">
<META NAME="description" CONTENT="Your number one source for custom made USDOT or US DOT Vinyl Stickers. Can be used for fleet vehicles or single haulers.">
<META NAME="author" CONTENT="Arron Lorenz">
<META NAME="ROBOTS" CONTENT="ALL">
<!-- Metadata generated by http://vancouver-webpages.com/META/mk-metas.html -->
</HEAD>
<link rel="stylesheet" type="text/css" href="./quicksticker.css" media="all" />
<!--[if IE]>
<style type="text/css" media="all">.borderitem {border-style:solid;}</style>
<![endif]-->
</head>

<body>


<H1 align="right">View Your Google Checkout Cart Above.</H1>
<a target="_parent" href="http://dotlettering.com/index.php?option=com_wrapper&view=wrapper&Itemid=38" <img src="http://www.dotlettering.com/php/landing/images/quicksticker-header.png" alt="PayPal" /> </a>


<div id="main">
	<img src="images/quicksticker_r1_c2.gif" id="quicksticker_r1_c2"  alt="7 Years Durable" />
		<img src="images/quicksticker_r1_c3.gif" id="quicksticker_r1_c3"  alt="" />
		<img src="images/quicksticker_r1_c5.gif" id="quicksticker_r1_c5"  alt="100% Free Shipping" />
		<br class="clearfloat" />
	<img src="images/quicksticker_r2_c2.gif" id="quicksticker_r2_c2"  alt="" />
		<br class="clearfloat" />
	<img src="images/quicksticker_r3_c2.gif" id="quicksticker_r3_c2"  alt="seperator line" />
		<br class="clearfloat" />
	<p class="Txt_DOTLettering">

		DOTLettering.com prides it self on offering the longest lasting vinyl we can at an affordable price! Owner/Operators and Large companies have relied on DOTLettering.com for more than lettering, our customers have come to expect the best quality, longest lasting, widest variety, and ease of application. Each and everyone of our orders is shipped for free. All of our custom products have a 90 day money back guarantee. If you&rsquo;re not satisfied with your order ship at back and we&rsquo;ll refund<br />%100 of your order the same day. Please don&rsquo;t hesitate to contact us for anything.<br /><br />Remember at DOTLettering.com our motto is:<br />&ldquo;US DOT Stickers should be Safe, Easy, and Legal!&rdquo;

	</p>
	<br class="clearfloat" />
	<img src="images/quicksticker_r5_c2.gif" id="quicksticker_r5_c2"  alt="seperator line" />
		<br class="clearfloat" />
	<div id="colwrap1">
		<img src="images/quicksticker_r6_c2.gif" id="quicksticker_r6_c2"  alt="7-10 Year Outdoor Durable Vinyl, Sticker Applies in one piece, Pick your size, choose and color or font, Money back guarantee" />
				<img src="images/quicksticker_r7_c2.gif" id="quicksticker_r7_c2"  alt="USDOT Vinyl Stickers $7.99 per set" />
			</div>
	<img src="images/quicksticker_r6_c4.gif" id="quicksticker_r6_c4"  alt="USDOT sticker examples, and color examples, View the styles below choose from any of the styes at no extra charge. Make your DOT numbers as creative as your rig. From Peterbilt to Ford" />
		<br class="clearfloat" />
	
	<div id="buyform1">

	
  <div class="product">
          
<input type="hidden" name="on0" value="Letter Height">
Letter Height: <select class="product-attr-size">
	<option  googlecart-set-product-price="$7.99" >2&quot; $7.99
	<option googlecart-set-product-price="$8.50" >2.5&quot; $8.50	
	<option googlecart-set-product-price="$9.50" >3&quot; $9.50
	<option googlecart-set-product-price="$10.99" >4&quot; $10.99
	<option googlecart-set-product-price="$13.99">5&quot; $13.99
	<option googlecart-set-product-price="$17.99" >6&quot; $17.99
</select>
<br>
<input type="hidden"  name="on1" value="Color">Color: 
<select class="product-attr-color"  name="color">
	<option value="Black">Black 
	<option value="White">White 
	<option value="Red">Red 
	<option value="Blue">Blue 
	<option value="Green">Green 
	<option value="Pink">Pink 
	<option value="Orange">Orange 
	<option value="Yellow">Yellow 
	<option value="Silver">Silver
</select>

<br>

<input type="hidden" name="on2" value="Font (Lettering Style)">Font (Lettering Style): 
<select class="product-attr-font"  name="font">
	<option value="Arial Black">Arial Black 
	<option value="Impact">Impact 
	<option value="Americana">Americana 
	<option value="Artcraft">Artcraft 
	<option value="Auburn">Auburn 
	<option value="Baker Signet">Baker Signet 
	<option value="Bank Gothic">Bank Gothic 
	<option value="Baskerville">Baskerville 
	<option value="Bauhaus">Bauhaus 
	<option value="Belwe">Belwe
	<option value="Bengel">Bengel
	<option value="Bernhard">Bernhard
	<option value="Birch">Birch
	<option value="Block">Block
	<option value="Bloom">Bloom
	<option value="Branding Iron">Branding Iron
	<option value="Broadway">Broadway
	<option value="Comic Sans">Comic Sans
	<option value="Computer">Computer
	<option value="Corsiva">Corsiva
	<option value="Courier">Courier
	<option value="Davida">Davida
	<option value="Egyption">Egyptian
	<option value="Flare">Flare
	<option value="Gem">Gem
	<option value="Gore">Gore
	<option value="Hobo">Hobo
	<option value="Impact">Impact
	<option value="Isbell">Isbell
	<option value="Korinna">Korinna
	<option value="March">March
	<option value="Mirarae">Mirarae
	<option value="Mobster">Mobster
	<option value="Moon">Moon
	<option value="Nueva">Nueva
	<option value="Orca">Orca
	<option value="Omega">Omega
	<option value="Paplar">Paplar
	<option value="Pointedly">Pointedly
	<option value="Poster">Poster
	<option value="Rounded">Rounded
	<option value="Cheap Fire">Cheap Fire
	<option value="Snow Caps">Snow Caps
	<option value="Thunderbird">Thunderbird	
</select>
#
<br>
<input type="hidden" value="Your USDOT number:">Your USDOT number:<input type="text" class="product-attr-USDOTnumber"  maxlength="30" >

*
<br><br>
<input type="hidden" class="product-price" value="$7.99">
<input type="hidden" class="product-shipping" value="$0.00">



<input class="product-title"  type="hidden" value="USDOT-Custom-SP1-1SET"/>
   
  <div  role="button" alt="Add to cart" tabindex="0" class="googlecart-add-button">
 
</div> </div>

<br><br>
<p>*Please be sure to type your DOT number<br>
exactly as you want it to be shown!<br><br>
#Please choose your fonts from<br>
the selection available below.

</p>

<script id="googlecart-script" type="text/javascript"
  src="http://checkout.google.com/seller/gsc/v2/cart.js?mid=637841941674076"
  currency="USD">
</script>

	</div>
		
</div>

<div id=fontsbelow>
View Fonts Below
</div>



<div id=fontpicsbody>
<img src="images/fonts/DOT-Fonts.gif" id="fontpictures"  alt="Fonts" />

<div id=fontpicsox>

</div>







</div>



<div id=analytics>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-553527-11");
pageTracker._trackPageview();
} catch(err) {}</script>

</div>



</body>
</html>